# -*- coding: utf-8 -*-

tables = {
  'DATA1' : {
    'coverage' : 'in_year',
    "col_defs" :  ["float", "str", "float", "float", "float", "float", "percentage", "float", "percentage", "float", "percentage"],
    'headers_e' :
    [[
      {'colspan': 2, 'header' : "Vote"},
      {'colspan': 5, 'header' : "2011-12"},
      {'colspan': 2, 'header' : "2012-13"},
      {'colspan': 2, 'header' : "5 Year Average**"}
    ],
      ["Vote Number",
       "Vote Description",

       "Authority",
       "Expenditures at Period 9",
       "Forecast Exenditures at year end",
       "Forecast Lapse (by EACPD*)",
       "Forecast Lapse (by EACPD*)",

       "Previous Year Gross Lapse (2010-11)",
       "Previous Year Gross Lapse Percentage (2010-11)",

       "5 Year Gross Lapse Average",
       "5 Year Gross Lapse Percentage",
      ]],
    'headers_f' :
    [[
      {'colspan': 2, 'header' : "Vote"},
      {'colspan': 5, 'header' : "2011-12"},
      {'colspan': 2, 'header' : "2012-13"},
      {'colspan': 2, 'header' : "Moyenne sur cinq ans** "}
    ],
      [
        "Numéro de crédit",
        "Nom du crédit",

        "Autorité",
        "Budgets Dépenses à la période 9",
        "Dépenses prévues à la fin de l'année",
        "Fonds inutilisés estimés par la DADPR*",
        "Fonds inutilisés estimés par la DADPR*",

        "Fonds inutilisés bruts de l'année précédente",
        "Fonds inutilisés bruts de l'année précédente en pourcentage",

        "Moyenne des fonds inutilisés bruts sur 5 ans",
        "Moyenne des fonds inutilisés bruts sur 5 ans en pourcentage",
      ]],
    'title_e' : 'Table 1 - Lapse Forecast for 2011-12 based on December data (P9) ($000)',
    'title_f' :  'Tableau 1 - Prévision des fonds inutilisés basée sur les dépenses de Décembre 2011 (P9)',
    'name' : 'Table 1',
    'nom' : 'Tableau 1',
    'dept_field' : 0,
    'start_row'  : 0,
    'keep_fields' : [2,4,5,6,7,8,11,12,13,14]
  },
  'DATA2': {
    'coverage' : 'in_year',
    "col_defs" : ["float", "str", "float", "float", "float", "float", "float", "float"],
    'headers_e' : [
      ["Vote Number / Stat Item",
       "Vote / Statutory Description",
       "Gross Appropriations",
       "Revenues",
       "Net Appropriations",
       "Gross Expenditures",
       "Revenues",
       "Net Expenditures"]],
    'headers_f' : [
      ["Numéro de Crédit / Statutaire",
       "Description des dépenses votées et statutaires",
       "Crédits bruts",
       "Recettes",
       "Crédits Net",
       "Dépenses brutes",
       "Recettes",
       "Dépenses nettes"]],
    'title_e' : "Table 2 - Authority and Expenditure based on August data (P5) ($000)",
    'title_f' :"Tableau 2 - Crédits et dépenses à la fin de Août 2011 (P5)  ($000)",
    'name' : 'Table 2',
    'nom' : 'Tableau 2',
    'dept_field' : 0,
    'start_row'  : 0,
    'keep_fields' : [8,9,10,11,12,13,14,15]
  },
'DATA2A' : {
  'coverage' : 'in_year',
  "col_defs" : ["str", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"],
  'headers_e' : [
    [
      {'colspan': 1, 'header' : "Program Activity"},
      {'colspan': 6, 'header' : "2011 - 12 Period 5"},
      {'colspan': 6, 'header' : "2010 - 11"},
      {'colspan': 6, 'header' : "2009 - 10"},
    ],
    [
      '',
      "Operating",
      "Capital",
      "Grants & Contrib.",
      "Other Votes",
      "Statutory",
      "Total 2013-12",
      "Operating",
      "Capital",
      "Grants & Contrib.",
      "Other Votes",
      "Statutory",
      "Total 2010-11",
      "Operating",
      "Capital",
      "Grants & Contrib.",
      "Other Votes",
      "Statutory",
      "Total 2009-10"
    ]
  ],
  'headers_f' : [
    [
      {'colspan': 1, 'header':  "Activites de programme"},
      {'colspan': 6, 'header':  "2011 - 12 Période 5"},
      {'colspan': 6, 'header':  "2010 - 11"},
      {'colspan': 6, 'header':  "2009 - 10"},
    ], [
      '',
      "Fonctionnement",
      "Capital",
      "Subventions & Contributions",
      "Autres Crédits",
      "Statutaires",
      "Total 2011-12",
      "Fonctionnement",
      "Capital",
      "Subventions & Contributions",
      "Autres Crédits",
      "Statutaires",
      "Total 2010-11",
      "Fonctionnement",
      "Capital",
      "Subventions & Contributions",
      "Autres Crédits",
      "Statutaires",
      "Total 2009-10", ]],
'title_e' : "Table 2A - Expenditures by Program Activity ($000)",
'title_f' : "Tableau 2A - Dépenses par Activité de programme ($000)",
'name' : 'Table 2a',
'nom' : 'Tableau 2a',
'start_row' :0,
'dept_field' : 0,
'keep_fields' : range(2,21)
},
'DATA2B' : {
  'coverage' : 'in_year',
  "col_defs" :["float", "str", "float", "float", "percentage", "float", "float", "percentage"],
  'headers_e' : [
    [
      {'colspan': 1, 'header' : "Vote Number"},
      {'colspan': 1, 'header' : "Vote Description"},
      {'colspan': 3, 'header' : "2011 - 12 Period 9"},
      {'colspan': 3, 'header' : "2010 - 11 Period 9"},
    ],
    [
      '',
      '',
      'Net Authority',
      'Net Expenditures',
      'Spending Rate',
      'Net Authority',
      'Net Expenditures',
      'Spending Rate'
    ]],
  'headers_f' : 
  [[
    {'colspan': 1, 'header' : "Numéro de Crédit"},
    {'colspan': 1, 'header' : "Description du Crédit"},
    {'colspan': 3, 'header' : "2011-12  Période 9"},
    {'colspan': 3, 'header' : "2010-11  Période 9"},
  ],
    [
      '',
      '',
      "Budgets nets",
      "Dépenses nettes",
      "Niveau de dépense",
      "Budgets nets",
      "Dépenses nettes",
      "Niveau de dépense",
    ]],
  'title_e' : "Table 2B - Spending Rate Comparison (2011-12 vs 2010-11)",
  'title_f' : "Tableau 2B - Niveau de dépense (2011-12 vs 2010-11)",
  'name' : 'Table 2b',
  'nom' : 'Tableau 2b',
  'start_row' : 1,
  'dept_field' : 0,
  'keep_fields' : [8] + range(10,16)
},
'DATA3' : {
  'coverage' : 'in_year',
  "col_defs" : ["float", "str", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float" ],
  'headers_e' : [
    [
      {'colspan' : 1, 'header' : "Vote Number"},
      {'colspan' : 1, 'header' : "Vote Description"},
      {'colspan' : 1, 'header' : "Gross Appropriations"},
      {'colspan' : 3, 'header' : "Revenues Credited to the Vote"},
      {'colspan' : 12 , 'header' : "Net Appropriations"},
    ],[
      '',
      '',
      "Gross Total",
      "Main Estimates",
      "Treasury Board Authorities",
      "Total Revenues",
      "Multi-year appropriations",
      "Main Estimates",
      "SE(A)",
      "SE(B)",
      "SE(C)",
      "Transfers from TB Vote 5 Gov. Contengencies",
      "Transfers from TB Vote 10 Gov. Wide Initiatives ",
      "Transfers from TB Vote 15 Compens. Adjustments  ",
      "Transfers from TB Vote 25 OBCF  ",
      "Transfers from TB Vote 30 Paylist Requirements ",
      "Transfers from TB Vote 33 CBCF ",
      "Net Total",
    ]],
  'headers_f' : [
    [
      {'colspan' : 1, 'header' : "Numéro de crédit"},
      {'colspan' : 1, 'header' : "Description du Crédit"},
      {'colspan' : 1, 'header' :  "Imputations brutes"},                  
      {'colspan' : 3, 'header' :  "Revenus à valoir sur le(s) crédit(s)"},
      {'colspan' : 12 , 'header': "Imputations nettes"},                  
    ],[
      '',
      '',
      "Total Brut",
      "Budget Principal",
      "Autorité du Conseil du du Trésor",
      "Total des Revenus",
      "Crédits pluri-annluels",
      "Budget principal",
      "Supp. A",
      "Supp. B",
      "Supp. C",
      "Transferts du crédit 5 du CT (Éventualités du gouvernement)",
      "Transferts du crédit 10 du CT (Initiatives pangouvernementales)",
      "Transferts du crédit 15 du CT (Rajustements à la rémunération)",
      "Transferts du crédit 25 du CT (Report du budget de fonctionnement)",
      "Transferts du crédit 30 du CT (Besoins en matière de rémunération)",
      "Transferts du crédit 30 du CT (Report du budget d'immobilisations)",
      "Total net" ]
  ],
'title_e' :"Table 3 - Appropriation by Authority ($000)" ,
'title_f' : "Tableau 3 - Appropriations par autorité   ($000)",
'name' : 'Table 3',
'nom' : 'Tableau 3',
'dept_field' : 0,
'start_row'  : 1,
'keep_fields' : [3]+range(4,18)+[19,20,21]
},
'DATA4' : {
  'coverage' : 'historical',
  "col_defs" : ["float", "str", "str", "float", "float", "float", "float", "percentage", "float", "percentage", "float", "float", "float", "float", "percentage"],
  'headers_e' : [
    [
      {'colspan' : 1, 'header' : "Vote Number 2010-11"},
      {'colspan' : 1, 'header' : "Vote Description"},
      {'colspan' : 1, 'header' : "Year"},
      {'colspan' : 5, 'header' : "Gross Lapse"},
      {'colspan' : 2, 'header' : "Forecast"},
      {'colspan' : 3, 'header' : "Gross Lapse Components"},
      {'colspan' : 2, 'header' : "Net Lapse"},
    ],[
      '',
      '',
      '',
      "Net Authority",
      "Net Expenditures",
      "Available next year",
      "Gross Lapse (Public Accounts)",
      "Gross Lapse Percentage (Public Accounts)(%)",
      "Department Forecast at P9",
      "Department Forecast at P9 (%)",
      "Frozen Allotment",
      "Special Purpose Allotment",
      "OBCF & CBCF Allowed",
      "Net Lapse",
      "Net Lapse (%)"
    ]],
  'headers_f' : [
    [
      {'colspan' : 1, 'header' : "Numéro de crédit 2010-11"},
      {'colspan' : 1, 'header' : "Description du cédit"},
      {'colspan' : 1, 'header' :"Année"},
      {'colspan' : 5, 'header' : "Fonds inutilisés bruts"},
      {'colspan' : 2, 'header' : "Prévisions"},
      {'colspan' : 3, 'header' : "Ajustements aux fonds inutilisés bruts"},
      {'colspan' : 2, 'header' : "Fonds inutilisés"},
    ],[
      '',
      '',
      '',
      "Autorités nettes",
      "Dépenses nettes",
      "Disponible dans les exercices ultérieurs",
      "Fonds inutilisés bruts",
      "Fonds inutilisés bruts (%)",
      "Prévision du ministére à P9",
      "Prévision du ministére à P9 (%)",
      "Fonds bloqués",
      "Fonds à fin déterminée inutilisés",
      "Budgets reportés",
      "Fonds inutilisés nets",
      "Fonds inutilisés nets (%)" 
    ]],
'dept_field' : 0,
'start_row'  : 0,
'name' : 'Table 4',
'nom' : 'Tableau 4',
'title_e' : "Table 4 - Gross and Net Lapses by Vote from 2006-07 to 2010-11 ($000)",
'title_f' : "Tableau 4 - Fonds inutilisés bruts et nets par crédit de 2006-07 à 2010-11 ($000)",
'keep_fields' : [5] + range( 7,20)
},
'DATA5' : {
  'coverage' : 'historical',
  "col_defs" : ["float", "str", "str", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"],
  'headers_e' : [
    [
      {'colspan' : 1, 'header' : "Vote Number 2010-11"},
      {'colspan' : 1, 'header' : "Vote Description"},
      {'colspan' : 1, 'header' : "Year"},
      {'colspan' : 3, 'header' : "total operating"},
      {'colspan' : 3, 'header' : "Capital"},
      {'colspan' : 3, 'header' : "Transfer Payments"},
      {'colspan' : 3, 'header' : "Special Purpose*"},
      {'colspan' : 3, 'header' : "Frozen"},
      {'colspan' : 3, 'header' : "Total"}
    ],
    [
      '',
      '',
      '',
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**"]],
  'headers_f' : [
    [
      {'colspan' : 1, 'header' : "Numéro de crédit 2010-11"},
      {'colspan' : 1, 'header' : "Description du cédit"},
      {'colspan' : 1, 'header' : "Année"},
      {'colspan' : 3, 'header' : "Fonctionnement"},
      {'colspan' : 3, 'header' : "Capital"},
      {'colspan' : 3, 'header' : "Paiements de Transfert"},
      {'colspan' : 3, 'header' : "Affectations à fin spéciale*"},
      {'colspan' : 3, 'header' : "Montants gelés"},
      {'colspan' : 3, 'header' : "Total"}
    ],
    [
      '',
      '',
      '',
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts**" ]],
'dept_field' : 0,
'start_row'  : 2,
'name' : 'Table 5',
'nom' : 'Tableau 5',
'title_e' : "Table 5 - Voted Expenditures by Allotment from 2006-07 to 20010-11($000)",
'title_f' : "Tableau 5 - Détail des dépenses votées par affectation de 2006-07 à 2010-11 ($000)",
'keep_fields' : [4] + range(6,25)
},
'DATA6': {
  'coverage' : 'historical',
  "col_defs" : ["float", "str", "str", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"],
  'headers_e' : [
    [
      {'colspan' : 1, 'header' : "Vote Number 2010-11"},
      {'colspan' : 1, 'header' : "Vote Description"},
      {'colspan' : 1, 'header' : "Year"},
      {'colspan' : 3, 'header' : "Personnel"},
      {'colspan' : 3, 'header' : "Other Operating Costs"},
      {'colspan' : 3, 'header' : "Revenues"},
      {'colspan' : 3, 'header' : "Total Spending"}
    ],
    [
      '',
      '',
      '',
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
      "Authority",
      "Expenditures",
      "Gross Lapse**",
    ]],
  'headers_f' : [
    [
      {'colspan' : 1, 'header' :  "Numéro de crédit 2010-11"},
      {'colspan' : 1, 'header' :  "Description du cédit"},
      {'colspan' : 1, 'header' :  "Année"},
      {'colspan' : 3, 'header' :  "Personnel"},
      {'colspan' : 3, 'header' :  "Autres coût de fonctionnement"},
      {'colspan' : 3, 'header' :  "Revenus"},
      {'colspan' : 3, 'header' :  "Total"}
    ],
    [
      '',
      '',
      '',
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts*",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts*",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts*",
      "Autorité",
      "Dépenses",
      "Fonds Périmés Bruts*" ]],
'title_e' : "Table 6 - Expenditures by Operating Allotment from 2006-07 to 2010-11 ($000)",
'title_f' : "Tableau 6 - Dépenses de fonctionnement par affectation de 2006-07 à 2010-11 ($000) ",
'name' : 'Table 6',
'nom' : 'Tableau 6',
'dept_field' : 0,
'start_row'  : 1,
'keep_fields' : [4] + range(6,19)
},
'DATA7' : {
  'coverage' : 'historical',
  "col_defs" : ["float", "str", "str", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"],
  'headers_e' : [
    [
      {'colspan' : 1, 'header' : "Vote Number 2010-11 / Statutory"},
      {'colspan' : 1, 'header' : "Vote Description / Statutory"},
      {'colspan' : 1, 'header' : "Year"},
      {'colspan' : 16, 'header' : "Standard Objects"},
    ],
    [
      '',
      '',
      '',
      "Personnel",
      "Transportation and communication",
      "Information",
      "Professional and special services",
      "Rentals",
      "Repair and maintenance",
      "Utilities, materials, and supplies",
      "Acquisition of land, buildings, and works",
      "Acquisition of machinery and equipment",
      "Transfer Payments",
      "Other subsidies and payments",
      "Public Debt Charges",
      "Total Gross Expenditues",
      "External Revenues",
      "Internal Revenues",
      "Total Net Expenditues"
    ]],
  'headers_f' : [
    [
      {'colspan' : 1, 'header' : "Num. de crédit 2010-11 / Stat."},
      {'colspan' : 1, 'header' : "Description du crédit / Statutaire"},
      {'colspan' : 1, 'header' : "Année"},
      {'colspan' : 16, 'header' : "Articles courants"},
    ],
    [
      '',
      '',
      '',
      "Personnel",
      "Transports et communications",
      "Information",
      "Services professionels et speciaux",
      "Location",
      "Services de réparation et d'entretien",
      "Services publics, fournitures et approv.",
      "Acquisition de terrains, batiments et ouvrages",
      "Acquisition de materiel et d'outillage",
      "Paiements de transfert",
      "Autres subventions et paiements",
      "Frais de la dette",
      "Total des dépenses brutes",
      "Revenus internes",
      "Revenus externes",
      "Total des dépenses nettes" 
    ]],
'title_e' : "Table 7 - Expenditures by Standard Object from 2007-08 to 2010-11 ($000)",
'title_f' : "Tableau 7 - Dépenses par article courant de 2007-08 à 2010-11 ($000)",
'name' : 'Table 7',
'nom' : 'Tableau 7',
'dept_field' : 0,
'start_row'  : 1,
'keep_fields' : range(3,22)
}
}
