# Services Intro
services_intro_title:
  en: Introduction to services
  fr: TODO
total_number_of_services:
  transform: [handlebars, markdown]
  en: |
    Total number of services in {{subject.name}}
  fr: |
    TODO
number_value_of_services:
  transform: [handlebars, markdown]
  en: |
    **{{number_of_services}} services**
  fr: |
    **{{number_of_services}} services**
pct_of_met_high_vol_services:
  transform: [handlebars, markdown]
  en: |
    % of {{gl_tt "High Volume Services" "HIGH_VOL_SERVICES"}} which met Service Standards
  fr: |
    TODO
pct_of_client_interaction_pts_online:
  en: |
    % of client interaction points available online
  fr: |
    TODO
pct_of_online_end_services:
  en: |
    % of services that are online end-to-end
  fr: |
    TODO

services_intro_gov:
  transform: [handlebars, markdown]
  en: | 
    Information on {{gl_tt "services" "SERVICE"}} provided by the **{{subject.name}}** has been visualized here, so that Canadians can track service performance. These visualizations include information on {{gl_tt "service standards" "STANDARD"}} and performance, volumetric data on applications for these services, and service fee information. Each service has its own page, and service data has been rolled-up, or aggregated at the Program, Department and Government-wide level. The source of these visualizations, the GC Service Inventory, is available on the open data portal. 
        
    The **GC Service Inventory** currently contains service data from **{{num_of_orgs_offering_services}} departments and agencies**, covering results from **{{services_year_2}}** to **{{services_year}}**
    
    Please provide us with any feedback on the service inventory by submitting a feedback form.
  fr: TODO
services_intro_dept:
  transform: [handlebars, markdown]
  en: | 
    Information on {{gl_tt "services" "SERVICE"}} provided by the **{{subject.name}}** has been visualized here, so that Canadians can track service performance. These visualizations include information on {{gl_tt "service standards" "STANDARD"}} and performance, volumetric data on applications for these services, and service fee information. Each service has its own page, and service data has been rolled-up, or aggregated at the Program, Department and Government-wide level. The source of these visualizations, the GC Service Inventory, is available on the open data portal. 
        
    The **Service Inventory** for **{{subject.name}}** currently contains service data from **{{num_of_programs_offering_services}} programs**, covering results from **{{services_year_2}}** to **{{services_year}}**
    
    Please provide us with any feedback on the service inventory by submitting a feedback form.
  fr: TODO

# Services list
list_of_provided_services_title:
  en: List of provided services
  fr: Liste des services offerts
list_of_provided_services_desc_dept:
  transform: [handlebars, markdown]
  en: |
    In **{{services_year}}, {{subject_name}}** offered **{{num_of_services}}** {{gl_tt "services" "SERVICE"}}:
  fr: |
    TODO
list_of_provided_services_desc_program:
  transform: [handlebars, markdown]
  en: |
    Programs can provide one or more {{gl_tt "services" "SERVICE"}}. As well, several Programs together may offer one service.

    In **{{services_year}}, {{subject_name}}** offered **{{num_of_services}}** services
  fr: TODO

view_service:
  en: Explore the service
  fr: Découvrez le service
filter_results_service:
  en: Filter services by name or type
  fr: Filtrer les services par nom ou par type   

# Digital Status
services_digital_status_text:
  transform: [handlebars, markdown]
  en: |
    Among the **{{number_of_services}}** {{gl_tt "services" "SERVICE"}} that **{{subject_name}}** offers, **{{fmt_big_int number_of_online_enabled_services}}** services are available online end-to-end, representing **{{fmt_percentage1 pct_of_online_services}}** of all services
  fr: |
    TODO
services_digital_status_prog_text:
  transform: [handlebars, markdown]
  en: |
    Among the **{{number_of_services}}** {{gl_tt "services" "SERVICE"}} that are delivered under the **{{subject_name}}** program, **{{most_digital_name}}** is the most commonly available online {{gl_tt "client interaction point" "CLIENT_INTERACTION"}} (**{{fmt_percentage1 most_digital_pct}}**) while **{{least_digital_name}}** is the least commonly available online {{gl_tt "client interaction point" "CLIENT_INTERACTION"}} (**{{fmt_percentage1 least_digital_pct}}**).
  fr: TODO
service_digital_status_most_and_least_same_text:
  transform: [handlebars, markdown]
  en: All of the services have the same online availability of client interaction points (**{{fmt_percentage1 least_digital_pct}}**).
  fr: TODO
services_digital_status:
  en: Online status of services
  fr: État des services en ligne
digital_status:
  en: Online status of this service
  fr: État en ligne de ce service
account_reg_digital_desc:
  en: Clients can register online
  fr: Les client peuvent s'inscire en ligne
application_digital_desc:
  en: Clients can apply online
  fr: Les clients peuvent présenter leur demande en ligne
authentication_desc:
  en: Clients can authenticate online
  fr: L'authentification du client peut se faire en lignne
decision_digital_desc:
  en: Department can inform decisions online
  fr: Le ministére peut transmettre ses décisions en ligne
issuance_digital_desc:
  en: Documentation can be issued online
  fr: La documentation peut être transmise en ligne
issue_res_digital_desc:
  en: Clients can provide feedback online
  fr: Les clients peuvent faire des commentaires en ligne
account_reg_digital:
  en: Registration
  fr: Inscription
application_digital:
  en: Application
  fr: Demande
authentication:
  en: Authentication
  fr: Authentification
decision_digital:
  en: Decision
  fr: Décision
issuance_digital:
  en: Issuance
  fr: Transmission
issue_res_digital:
  en: Feedback
  fr: Rétroaction
can_online:
  en: Yes (can be done online)
  fr: Oui (Peut se faire en ligne)
cannot_online:
  en: No (cannot be done online)
  fr: Non (Ne peut pas se faire en ligne)
client_interaction_point:
  en: Client Interaction Points
  fr: Points d'interaction liés aux clients

# Channels
service_name:
  en: Service name
  fr: Nom du service
services_channels_title:
  en: Applications for Services by Channel
  fr: TODO
single_service_channels_title:
  en: Application channels of this service
  fr: TODO
services_channels_text:
  transform: [handlebars, markdown]
  en: Among the **{{fmt_big_int number_of_applications}}** applications which the **{{subject.name}}** received across **{{number_of_services}}** {{gl_tt "services" "SERVICE"}}, **{{fmt_big_int number_of_online_applications}}** applications were completed online, representing **{{fmt_percentage1  pct_of_online_applications}}** of all applications.
  fr: TODO
application_channels_by_services_text:
  transform: [handlebars, markdown]
  en: |
    Application channels that {{gl_tt "services" "SERVICE"}} use for handling applications.
    
    In **{{subject.name}}**, the most traffic was generated through "**{{max_vol_channel_name}}**", with a total of **{{fmt_big_int max_vol_channel_value}}** applications.

    The "**{{max_vol_service_name}}**" service received **{{fmt_big_int max_vol_service_value}}** applications, the highest among all of the department's services.
  fr: |
    TODO
application_channels_by_services_program_text:
  transform: [handlebars, markdown]
  en: |
    Application channels that {{gl_tt "services" "SERVICE"}} use for handling applications.

    Under the **{{subject.name}}** program, the most traffic was generated through the "**{{max_vol_channel_name}}**", with a total of **{{fmt_big_int max_vol_channel_value}}** applications.
    
    The "**{{max_vol_service_name}}**" service received **{{fmt_big_int max_vol_service_value}}** applications, the highest among all of the services offered under this program.
  fr: TODO
service_channels_text:
  transform: [handlebars, markdown]
  en: |
    Application channels that this {{gl_tt "service" "SERVICE"}} uses for handling applications.
    
    {{#if max_channel_key}}There were **{{fmt_big_int max_value}} {{max_channel_key}}**, which is the highest Application channels volume for this service.{{/if}}
  fr: | 
    TODO
live_application_count:
  en: In person applications
  fr: Demandes en personne
mail_application_count:
  en: Applications by mail
  fr: Demandes par la poste
online_application_count:
  en: Online applications
  fr: Demandes en ligne
other_application_count:
  en: Applications by other channels
  fr: Demandes par d'autres moyens
online_inquiry_count:
  en: Website visits
  fr: Visites sur le site web
applications_count:
  en: applications
  fr: demandes

# Orgs offering services
orgs_offering_services_title:
  en: Organizations which offer services
  fr: TODO
programs_offering_services_title:
  en: Programs in this department which offer services
  fr: TODO
orgs_offering_services_text:
  transform: [handlebars, markdown]
  en: In **{{services_year}}, {{number_of_depts}}** departments and agencies of **{{subject.name}}** accepted **{{fmt_big_int number_of_applications}}** applications via **{{number_of_services}}** {{gl_tt "services" "SERVICE"}}
  fr: TODO
programs_offering_services_text:
  transform: [handlebars, markdown]
  en: In **{{services_year}}, {{number_of_programs}}** programs of **{{subject.name}}** accepted **{{fmt_big_int number_of_applications}}** applications via **{{number_of_services}}** {{gl_tt "services" "SERVICE"}}
  fr: TODO
number_of_services:
  en: Number of services
  fr: TODO
applications:
  en: Applications
  fr: TODO

# Overview
overview_digital_status_title:
  transform: [handlebars, markdown]
  en: What {{gl_tt "client interaction points" "CLIENT_INTERACTION"}} of this {{gl_tt "service" "SERVICE"}} are available online?
  fr: Quels {{gl_tt "points d'interaction liés aux clients" "CLIENT_INTERACTION"}} de ce service sont disponibles en ligne?
overview_digital_status_desc:
  en: Online client interaction points of this service
  fr: Points d'interaction en ligne liés aux clients de ce service
online_status:
  en: Online status
  fr: État en ligne
service_overview_title:
  en: Overview
  fr: Aperçu
related_programs:
  en: Related Programs
  fr: Programmes connexes
services_fees:
  en: Service fees
  fr: Frais de service
does_charge_fees:
  transform: [handlebars, markdown]
  en: This {{gl_tt "service" "SERVICE"}} **does** charge fees
  fr: |
    {{gl_tt "Service" "SERVICE"}} **payant**
does_not_charge_fees:
  transform: [handlebars, markdown]
  en: This {{gl_tt "service" "SERVICE"}} **does not** charge fees
  fr: |
    {{gl_tt "service" "SERVICE"}} **sans frais**
standards_performance_text:
  transform: [handlebars, markdown]
  en: Overall {{gl_tt "standards" "STANDARD"}} performance for this {{gl_tt "service" "SERVICE"}}
  fr: Rendement global des {{gl_tt "normes" "STANDARD"}} pour ce {{gl_tt "service" "SERVICE"}}
service_single_link_text:
  transform: [handlebars, markdown]
  en: More details on this {{gl_tt "service" "SERVICE"}} can be found **{{ext_link "here" service_url }}**
  fr: Pour en savoir plus sur ce {{gl_tt "service" "SERVICE"}}, cliquez **{{ext_link "ici" service_url }}**
service_links_text:
  transform: [handlebars, markdown]
  en: More details on this {{gl_tt "service" "SERVICE"}} can be found in the links below
  fr: Pour en savoir plus sur ce {{gl_tt "service" "SERVICE"}}, voir les lienns ci-dessous
service_link_text:
  en: More details (external links)
  fr: Pour en savoir plus (liens externes)
service_url:
  en: Service Link
  fr: Lien de service
standard_url:
  en: Service Standards and Targets Link
  fr: Lien des normes de service et les cibles
rtp_url:
  en: Real-time Performance Results Link
  fr: Lien des résultats du rendement en temps réel
identification_methods:
  en: Identification methods
  fr: Méthodes d'identification
uses_cra_as_identifier:
  en: Uses CRA business number as an identifier
  fr: Le numéro d'entreprise de l'ARC est utilisé comme identifiant
uses_sin_as_identifier:
  en: Uses Social Insurance Number as an identifier
  fr: Le NAS est utilisé comme identifiant
service_types:
  en: Service Types
  fr: Types de service

# Standard
service_standards_title:
  en: Service Standards
  fr: Normes de service
service_standards_text:
  transform: [handlebars, markdown]
  en: |
    {{gl_tt "Service standards" "STANDARD"}} are used as metrics to indicate how the {{gl_tt "service" "SERVICE"}} is doing.
  fr: |
    Les {{gl_tt "normes de service" "STANDARD"}} permettent de mesurer l'efficacité du {{gl_tt "service" "SERVICE"}}.
no_service_standards_text:
  en: This service does not have any service standards
  fr: Ce service n'a pas de normes de service
standard_name:
  en: Standard name
  fr: Norme de service
standard_type:
  en: Standard type
  fr: Type de norme de service
standard_channel:
  en: Standard channel
  fr: Mode de prestation
total_business_volume:
  en: Total Business Volume
  fr: Volume d'activités total
satisfied_business_volume:
  en: Satisfied Business Volume
  fr: Volume d'activités satisfaisant
has_standards:
  en: Service has standards
  fr: Le service a des normes
no_standards:
  en: Service does not have standards
  fr: Le service n’a pas de normes
target_met_true:
  en: Standard target is met
  fr: La cible standard est atteinte
target_met_false:
  en: Standard target is not met
  fr: La cible standard n’est pas atteinte
has_standards_text:
  transform: [handlebars, markdown]
  en: How many {{gl_tt "services" "SERVICE"}} have {{gl_tt "standards" "STANDARD"}}?
  fr: Combien de {{gl_tt "services" "SERVICE"}} ont des {{gl_tt "normes" "STANDARD"}}?
has_standards_table_text:
  en: How many services have standards?
  fr: Combien de services ont des normes?
target_met_text:
  transform: [handlebars, markdown]
  en: How many {{gl_tt "standards'" "STANDARD"}} targets were met?
  fr: Combien de cibles {{gl_tt "normes de service" "STANDARD"}} ont été atteintes?
target_met_table_text:
  en: How many standards' targets were met?
  fr: Combien de cibles normes ont été atteintes?
gauge_has_standards_text:
  transform: [handlebars, markdown]
  en: |
    **{{fmt_percentage1 has_standards_pct}}** of services have standards
  fr: |
    **{{fmt_percentage1 has_standards_pct}}** des services ont des normes
gauge_standards_met_text:
  transform: [handlebars, markdown]
  en: |
    **{{fmt_percentage1 standards_met_pct}}** of standards' targets were met
  fr: |
    **{{fmt_percentage1 standards_met_pct}}** des cibles normalisées ont été atteintes