services_intro_title:
  en: Service Inventory
  fr: Répertoire de services

services_intro_text:
  en: The Service Inventory provides a corporate-wide perspective on information related to Government of Canada services.
  fr: Répertoire de services fournit une perspective pangouvernementale des services du gouvernement du Canada.

services_fees_title:
  en: Service Fees
  fr: TODO

services_fees_text:
  en: TODO
  fr: TODO

has_fees:
  en: Has fees
  fr: TODO

no_fees:
  en: No fees
  fr: TODO

uses_CRA:
  en: Uses CRA Business Number as identifier
  fr: TODO

no_CRA:
  en: Does not use CRA Business Number as identifier
  fr: TODO

uses_SIN:
  en: Uses SIN as identifier
  fr: TODO

no_SIN:
  en: Does not use SIN as identifier
  fr: TODO

label_sin_is_identifier:
  en: Uses SIN as identifier
  fr: TODO

label_cra_buisnss_number_is_identifier:
  en: Uses CRA Business Number as identifier
  fr: TODO

label_telephone_enquires:
  en: Telephone enquiries
  fr: TODO

label_website_visits:
  en: Website visits
  fr: TODO

label_online_applications:
  en: Online applications
  fr: TODO

label_in_person_applications:
  en: In person applications
  fr: TODO

label_mail_applications:
  en: Applications by mail
  fr: TODO

label_other_channel_applications:
  en: Applications by other channels
  fr: TODO

communication_channels_title:
  en: Communication channels
  fr: TODO

communication_channels_text:
  en: How do services receive enquiries and applications, and what feedback channels are available?
  fr: TODO

services_ids_title:
  en: Identification methods
  fr: TODO

services_ids_text:
  en: Insert text here
  fr: TODO

digital_status_title:
  en: Digital status
  fr: TODO

services_digital_status_text:
  en: Information about the digital availability of different service steps. Double check the text labels for these things, I had to do some guessing.
  fr: TODO

account_reg_digital_status:
  en: Account registration
  fr: TODO

authentication_status:
  en: Authentication
  fr: TODO

application_digital_status:
  en: Application
  fr: TODO

decision_digital_status:
  en: Decision
  fr: TODO

issuance_digital_status:
  en: Issuance
  fr: TODO

issue_res_digital_status:
  en: Issue resolution
  fr: TODO

digital_option_available:
  en: Digital option available
  fr: TODO

digital_option_not_available:
  en: No digital option
  fr: TODO

services_unknown:
  en: Unknown / no data
  fr: TODO