services_intro_title:
  en: Service Inventory
  fr: Répertoire de services

services_intro_text:
  en: The Service Inventory provides a corporate-wide perspective on information related to Government of Canada services.
  fr: Répertoire de services fournit une perspective pangouvernementale des services du gouvernement du Canada.

services_fees_title:
  en: Service Fees
  fr: TODO

services_fees_text:
  en: TODO
  fr: TODO

has_fees:
  en: Has fees
  fr: TODO

no_fees:
  en: No fees
  fr: TODO

uses_CRA:
  en: Uses CRA Business Number as identifier
  fr: TODO

no_CRA:
  en: Does not use CRA Business Number as identifier
  fr: TODO

uses_SIN:
  en: Uses SIN as identifier
  fr: TODO

no_SIN:
  en: Does not use SIN as identifier
  fr: TODO

label_sin_is_identifier:
  en: Uses SIN as identifier
  fr: TODO

label_cra_buisnss_number_is_identifier:
  en: Uses CRA Business Number as identifier
  fr: TODO

label_telephone_enquires:
  en: Telephone enquiries
  fr: TODO

label_website_visits:
  en: Website visits
  fr: TODO

label_online_applications:
  en: Online applications
  fr: TODO

label_in_person_applications:
  en: In person applications
  fr: TODO

label_mail_applications:
  en: Applications by mail
  fr: TODO

label_other_channel_applications:
  en: Applications by other channels
  fr: TODO

communication_channels_title:
  en: Communication channels
  fr: TODO

communication_channels_text:
  en: How do services receive enquiries and applications, and what feedback channels are available?
  fr: TODO

services_ids_title:
  en: Identification methods
  fr: TODO

services_ids_text:
  en: Insert text here
  fr: TODO