// This file is automatically generated.
// Please do not change this file!
export const maxBreakpointOffset: string;
export const minSmallDevice: string;
export const maxSmallDevice: string;
export const minMediumDevice: string;
export const maxMediumDevice: string;
export const minLargeDevice: string;
export const maxLargeDevice: string;
export const minExtraLargeDevice: string;
export const maxExtraLargeDevice: string;