// This file is automatically generated.
// Please do not change this file!
export const primaryColor: string;
export const secondaryColor: string;
export const tertiaryColor: string;
export const backgroundColor: string;
export const highlightColor: string;
export const separatorColor: string;
export const buttonPrimaryColor: string;
export const buttonSecondaryColor: string;
export const textColor: string;
export const textLightColor: string;
export const textGreen: string;
export const textRed: string;
export const linkColor: string;
export const linkFocusColor: string;
export const linkVisitedColor: string;
export const highlightPaleColor: string;
export const highlightOrangeColor: string;
export const highlightDarkColor: string;
export const successLightColor: string;
export const successDarkColor: string;
export const failLightColor: string;
export const failDarkColor: string;
export const warnLightColor: string;
export const warnDarkColor: string;
export const infoLightColor: string;
export const infoDarkColor: string;