// This file is automatically generated.
// Please do not change this file!
export const fontFamily: string;
export const lightFontWeight: string;
export const mediumFontWeight: string;
export const heavyFontWeight: string;