// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundColor': string;
  'buttonPrimaryColor': string;
  'buttonSecondaryColor': string;
  'failDarkColor': string;
  'failLightColor': string;
  'fontFamily': string;
  'heavyFontWeight': string;
  'highlightColor': string;
  'highlightDarkColor': string;
  'highlightOrangeColor': string;
  'highlightPaleColor': string;
  'infoDarkColor': string;
  'infoLightColor': string;
  'lightFontWeight': string;
  'linkColor': string;
  'linkFocusColor': string;
  'linkVisitedColor': string;
  'maxExtraLargeDevice': string;
  'maxLargeDevice': string;
  'maxMediumDevice': string;
  'maxSmallDevice': string;
  'mediumFontWeight': string;
  'minExtraLargeDevice': string;
  'minLargeDevice': string;
  'minMediumDevice': string;
  'minSmallDevice': string;
  'primaryColor': string;
  'secondaryColor': string;
  'separatorColor': string;
  'standardBorderRadius': string;
  'successDarkColor': string;
  'successLightColor': string;
  'tertiaryColor': string;
  'textColor': string;
  'textGreen': string;
  'textLightColor': string;
  'textRed': string;
  'warnDarkColor': string;
  'warnLightColor': string;
}
export const cssExports: CssExports;
export default cssExports;
